sign-commit = false
sign-tag = false
push = true
publish = false
pre-release-commit-message = "chore: release effectengine v{{version}}"
tag-message = "effectengine v{{version}}"
tag-name = "effectengine-v{{version}}"
